### PR TITLE
Feature/receptable

### PR DESCRIPTION
**Pull request by Condordito**
### Additions
-  `meta.slot` context variable on click
- `setElement`  overload for `Receptacle`

Currently, it is not possible to update or perform actions on a single icon slot if it has multiple positions. `meta.slot` would make these interactions manageable.

Overloading `setElement` in `Receptacle` to take a single slot would eliminate unnecessary arrays while iterating through another collection.

### Usage
Untitled

### CODE REVIEW

**Comment by TheFloodDragon** [comment]
`setElement` for JavaScript support?
It isn't necessary as usual.

**Comment by Condordito** [comment]
it makes creating more complex layouts a lot easier

**Comment by Condordito** [comment]
_Here's another example_:
Demo

It uses the `setElement` overload to display the icons, and `meta.slot` to handle all interactions. This is done after calculating the pages needed and sorting/filtering its content. 

```yml
Layout:
  - 'QQQQQQQQS'
  - 'QQQQQQQQN'
  - 'QQQQQQQQP'
  - 'QQQQQQQQF'

Icons: 
  Q:
    display.material: AIR
    actions.all: 
    - condition: '$ q = meta.icons[meta.slot]; q != undefined && q.is_trackable'
      actions: 'js: funcs("toggleTracking")'
  N: 
    display:
      material: 'source:HDB:8787'
      name: "&7Next Page"
    actions.all:
    - condition: "$ meta.current_page != meta.max_pages"
      actions: 
      - 'js: session.receptacle.setElement(null, utils.getIconSlots("Q", session), true)'
      - 'js: meta.current_page = meta.current_page + 1; funcs("loadIcons") <delay:1>'
  ...

Functions:
...
  loadIcons: |-
    meta.icons = {};
    var builder = utils.getItemBuildr(); builder.hideAll(); 
    var pageSetting = meta.pages[meta.current_page] || {};
    utils.getIconSlots("Q", session).forEach(function(slot) {
      var questIndex = pageSetting[slot]
      if (questIndex == undefined) {
        session.receptacle.setElement(null, slot, true);
        return;
      }
      var quest = meta.computed[questIndex]
      builder.name = quest.name
      ...
      if(quest.is_trackable) {
        var tracked = vars("%javascript_tab_active,${quest.id}%") == "true"
        builder.lore.addAll(["", "§5§lCLICK TO ${tracked ? 'UNTRACK' : 'TRACK'}"])
      }
      session.receptacle.setElement(builder.build(), slot, true);
      meta.icons[slot] = quest;  
      builder.lore.clear();
    })
```

**Comment by TheFloodDragon** [comment]
I'm sorry, I just don't see what the use it does
`setElement(element: ItemStack?, slot: Int, display: Boolean)` seems the same as `setElement(element: ItemStack?, vararg slots: Int, display: Boolean)` (Just pass a single argument, **single slot**)

**Comment by Condordito** [comment]
It gets compiled as a single-element array if called using Kotlin. But in JS, it will throw an error since `setElement(element: ItemStack?, slot: Int, display: Boolean)` is not part of its method signature.

_Kotlin code:_
Screenshot 2024-05-11 at 7 23 58 AM
_Compiled:_
Screenshot 2024-05-11 at 7 21 58 AM
_Error from Nashorn:_
Screenshot 2024-05-11 at 7 19 16 AM

**Comment by Condordito** [comment]
@TheFloodDragon 

Also, when `setElement(element: ItemStack?, slot: Int, display: Boolean)` is added, Kotlin compiler will take that signature instead of using `setElement(element: ItemStack?, slot: int[], display: Boolean)`

Screenshot 2024-05-11 at 7 37 43 AM

**Comment by TheFloodDragon** [comment]
All right, then I won't care.

**Pull request merged**
